# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(.versionbot/|LICENSE|CHANGELOG.md|VERSION|README.md)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents]

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck

-   repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
    -   id: shfmt-docker

-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
    -   id: actionlint

-   repo: https://github.com/MarketSquare/robotframework-robocop
    rev: v8.2.2
    hooks:
    -   id: robocop
    -   id: robocop-format
